/*------------------------------------------------------------
File: delay.c
Purpose: Implements software delay functions using super loop method.
Working Principle:
    Delay is generated by executing empty loop instructions.
    Each loop iteration consumes fixed CPU clock cycles.
Important:
    This delay is NOT accurate.
    It depends on:
        - CPU clock frequency
        - Compiler optimization level
------------------------------------------------------------*/

//------------------------------------------------------------
// Function: delay_us
// Purpose : Delay for given microseconds using Superloop
//------------------------------------------------------------
void delay_us(unsigned int tdly)
{
	tdly*=12;
	while(tdly--);
}
//------------------------------------------------------------
// Function: delay_ms
// Purpose : Delay for given milliseconds using Superloop
//------------------------------------------------------------
void delay_ms(unsigned int tdly)
{
	tdly*=12000;
	while(tdly--);
}
//------------------------------------------------------------
// Function: delay_s
// Purpose : Delay for given seconds using Superloop
//------------------------------------------------------------
void delay_s(unsigned int tdly)
{
	tdly*=12000000;
	while(tdly--);
}
